import type { ResourceDef } from '../schema.js';
import { BASE, DO_GRUPO, ID, UFS, opcoes, sn } from './comum.js';

/** Usuários, níveis e empresas (filiais) do grupo — telas Usuários e Empresas do Delphi (nível A) */
export const RECURSOS_ACESSO: ResourceDef[] = [
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'usuarios',
    table: 'usuarios',
    label: 'Usuários',
    labelSingular: 'Usuário',
    description: 'Usuários do grupo, nível de acesso e empresas liberadas',
    icon: 'UserCog',
    group: 'sistema',
    labelField: 'nome',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      { name: 'apelido', label: 'Apelido', type: 'text', listed: true, searchable: true, maxLength: 15 },
      { name: 'nome', label: 'Usuário', type: 'text', required: true, listed: true, searchable: true, maxLength: 30, width: 'md' },
      { name: 'email', label: 'E-mail', type: 'text', required: true, listed: true, searchable: true, maxLength: 50, width: 'lg', hint: 'É o login do usuário' },
      {
        name: 'senha',
        label: 'Senha',
        type: 'password',
        senhaLegada: true,
        maxLength: 15,
        hint: 'Em branco na alteração: mantém a senha atual. Gravada como no PrintControl Delphi (que usa a mesma tabela)',
      },
      { name: 'nivel', label: 'Nível', type: 'text', required: true, listed: true, filterable: true, width: 'sm', ref: { resource: 'usuarios_niveis', labelField: 'descricao' } },
      { name: 'pagina_web', label: 'Página inicial', type: 'text', maxLength: 80, span: 2, hint: 'Endereço aberto na tela inicial (Home)' },
      sn('recebe_email', 'Recebe e-mail'),
      sn('ativo', 'Ativo', { listed: true, filterable: true, default: true }),
    ],
    filtroRapido: 'ativo',
    filtroRapidoPadrao: '1',
  },
  {
    ...BASE,
    name: 'usuarios_niveis',
    table: 'usuarios_niveis',
    label: 'Níveis de usuário',
    labelSingular: 'Nível',
    description: 'Letras de nível (A = administrador; quanto menor a letra, maior o acesso)',
    icon: 'KeyRound',
    group: 'sistema',
    oculto: true,
    autoIncrement: false,
    labelField: 'descricao',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      { name: 'id', label: 'Letra', type: 'text', required: true, listed: true, maxLength: 1, width: 'xs' },
      { name: 'nivel', label: 'Sigla', type: 'text', listed: true, maxLength: 2, width: 'xs' },
      { name: 'descricao', label: 'Descrição', type: 'text', required: true, listed: true, maxLength: 25 },
    ],
  },
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'empresas',
    table: 'empresas_filiais',
    label: 'Empresas',
    labelSingular: 'Empresa',
    description: 'Empresas (filiais) do grupo: dados fiscais, certificado, contatos e modelo de contrato',
    icon: 'Building2',
    group: 'sistema',
    labelField: 'apelido',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      { name: 'apelido', label: 'Apelido', type: 'text', required: true, listed: true, searchable: true, maxLength: 15, secao: 'Empresa' },
      { name: 'nome_comercial', label: 'Nome comercial', type: 'text', listed: true, searchable: true, maxLength: 50, span: 2, secao: 'Empresa' },
      { name: 'razao_social', label: 'Razão social', type: 'text', listed: true, searchable: true, maxLength: 80, span: 2, secao: 'Empresa' },
      { name: 'cnpj', label: 'CNPJ', type: 'cnpj', listed: true, searchable: true, secao: 'Empresa' },
      { name: 'ie', label: 'IE', type: 'text', maxLength: 20, secao: 'Empresa' },
      { name: 'simples_normal', label: 'Regime', type: 'enum', options: opcoes([['S', 'Simples Nacional'], ['N', 'Normal']]), secao: 'Empresa' },
      { name: 'representante_legal_nome', label: 'Representante legal', type: 'text', maxLength: 50, span: 2, secao: 'Empresa' },
      { name: 'representante_legal_cpf', label: 'CPF do representante', type: 'cnpj', secao: 'Empresa' },
      { name: 'cep', label: 'CEP', type: 'text', maxLength: 8, secao: 'Endereço' },
      { name: 'endereco', label: 'Endereço', type: 'text', maxLength: 50, span: 2, secao: 'Endereço' },
      { name: 'numero', label: 'Nr.', type: 'text', maxLength: 5, secao: 'Endereço' },
      { name: 'bairro', label: 'Bairro', type: 'text', maxLength: 30, secao: 'Endereço' },
      { name: 'cod_cidade', label: 'Cód. cidade (IBGE)', type: 'text', maxLength: 7, secao: 'Endereço' },
      { name: 'cidade', label: 'Cidade', type: 'text', listed: true, searchable: true, filterable: true, maxLength: 50, secao: 'Endereço' },
      { name: 'uf', label: 'UF', type: 'enum', listed: true, filterable: true, options: UFS, width: 'xs', secao: 'Endereço' },
      { name: 'latitude', label: 'Latitude', type: 'decimal', scale: 6, allowNegative: true, secao: 'Endereço' },
      { name: 'longitude', label: 'Longitude', type: 'decimal', scale: 6, allowNegative: true, secao: 'Endereço' },
      { name: 'arquivo_pfx', label: 'Certificado (.pfx)', type: 'text', readOnly: true, secao: 'NF-e', hint: 'Enviado pela ação "Upload .PFX" da lista' },
      { name: 'senha_pfx', label: 'Senha do certificado', type: 'password', senhaLegada: true, maxLength: 30, secao: 'NF-e', hint: 'Em branco: mantém a atual' },
      { name: 'nfe_ambiente', label: 'Ambiente', type: 'enum', listed: true, options: opcoes([['P', 'PRODUÇÃO'], ['H', 'HOMOLOGAÇÃO']]), default: 'P', secao: 'NF-e' },
      { name: 'contato_financeiro', label: 'Contato financeiro', type: 'text', maxLength: 50, secao: 'Depto. Financeiro' },
      { name: 'email_financeiro', label: 'E-mail financeiro', type: 'text', maxLength: 100, span: 2, secao: 'Depto. Financeiro' },
      { name: 'contato_compras', label: 'Contato compras', type: 'text', maxLength: 50, secao: 'Depto. Compras' },
      { name: 'email_compras', label: 'E-mail compras', type: 'text', maxLength: 100, span: 2, secao: 'Depto. Compras' },
      { name: 'contato_diretoria', label: 'Contato diretoria', type: 'text', maxLength: 50, secao: 'Diretoria' },
      { name: 'email_diretoria', label: 'E-mail diretoria', type: 'text', maxLength: 100, span: 2, secao: 'Diretoria' },
    ],
  },
];
