import type { FieldDef, ResourceDef } from '../schema.js';
import { BASE, DO_GRUPO, DA_EMPRESA, ID, UFS, opcoes, sn } from './comum.js';

/** Cadastro simples com uma coluna "Descrição" (marcas, tipos, famílias) */
const descricao = (maxLength: number): FieldDef => ({ name: 'descricao', label: 'Descrição', type: 'text', required: true, listed: true, searchable: true, maxLength, width: 'lg' });

const simples = (name: string, label: string, labelSingular: string, description: string, maxLength: number): ResourceDef => ({
  ...BASE,
  ...DO_GRUPO,
  name,
  table: name,
  label,
  labelSingular,
  description,
  icon: 'Tag',
  group: 'cadastros',
  oculto: true,
  labelField: 'descricao',
  defaultSort: { field: 'descricao', dir: 'asc' },
  fields: [ID, descricao(maxLength)],
});

/** Código digitado (char) que é a PK junto com id_grupo/id_empresa: planos e séries */
const CODIGO: FieldDef = { name: 'id', label: 'Id', type: 'text', required: true, listed: true, searchable: true, maxLength: 3, width: 'xs', hint: 'Código de até 3 letras' };

/** Telas Equipamentos, Produtos, Tabelas e Estoque do Delphi (nível A) */
export const RECURSOS_CADASTROS: ResourceDef[] = [
  // ---------------------------------------------------------------- Equipamentos
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'equipamentos',
    table: 'equipamentos',
    label: 'Equipamentos',
    labelSingular: 'Equipamento',
    description: 'Impressoras do grupo, com o cliente do contrato ativo',
    icon: 'Printer',
    group: 'cadastros',
    labelField: 'nr_serie',
    // Delphi: ordem padrão p.nome (cliente atual), depois id
    defaultSort: { field: 'cliente_atual', dir: 'asc' },
    fields: [
      { ...ID, label: 'ID#' },
      { name: 'id_tipo', label: 'Tipo', type: 'number', listed: true, filterable: true, width: 'sm', ref: { resource: 'equipamentos_tipos', labelField: 'descricao' } },
      { name: 'id_marca', label: 'Marca', type: 'number', required: true, listed: true, filterable: true, width: 'sm', ref: { resource: 'equipamentos_marcas', labelField: 'descricao' } },
      { name: 'modelo', label: 'Modelo', type: 'text', listed: true, searchable: true, filterable: true, maxLength: 25 },
      {
        name: 'nr_serie',
        label: 'Nr. Série',
        type: 'text',
        listed: true,
        searchable: true,
        filterable: true,
        maxLength: 30,
        hint: 'Em branco: o sistema gera "PC" + 8 caracteres (botão Gerar NS do Delphi)',
      },
      { name: 'data_aquisicao', label: 'Aquisição', type: 'date', listed: true, filterable: true },
      { name: 'valor_aquisicao', label: 'Valor Aquisição R$', type: 'decimal', scale: 2, listed: true, default: '0' },
      { name: 'descricao', label: 'Descrição', type: 'text', required: true, listed: true, searchable: true, maxLength: 255, span: 2 },
      sn('usa_cilindro', 'Cilindro', { listed: true, filterable: true, default: false }),
      {
        name: 'cliente_atual',
        label: 'Cliente Atual',
        type: 'text',
        listed: true,
        searchable: true,
        filterable: true,
        // Contrato ativo mais recente (no Delphi, com 2+ ativos o MySQL escolhia um qualquer)
        sql: "(SELECT P.nome FROM locacao_contratos C JOIN pessoas P ON P.id = C.id_cliente WHERE C.id_equip = t.id AND C.ativo <> 'N' ORDER BY C.id DESC LIMIT 1)",
      },
    ],
  },
  simples('equipamentos_marcas', 'Marcas de equipamentos', 'Marca', 'Marcas dos equipamentos', 30),
  simples('equipamentos_tipos', 'Tipos de equipamentos', 'Tipo', 'Tipos dos equipamentos', 30),

  // ---------------------------------------------------------------- Produtos
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'produtos',
    table: 'produtos',
    label: 'Produtos',
    labelSingular: 'Produto',
    description: 'Produtos e peças, com família/grupo, marca e estoque',
    icon: 'Package',
    group: 'cadastros',
    labelField: 'descricao',
    defaultSort: { field: 'descricao', dir: 'asc' },
    fields: [
      { ...ID, label: 'ID#' },
      { name: 'descricao', label: 'Descrição', type: 'text', required: true, listed: true, searchable: true, filterable: true, maxLength: 60, span: 2, width: 'lg' },
      { name: 'id_marca', label: 'Marca', type: 'number', listed: true, filterable: true, width: 'sm', ref: { resource: 'produtos_marcas', labelField: 'descricao' } },
      {
        name: 'id_familia_grupo',
        label: 'Família / Grupo',
        type: 'number',
        listed: true,
        width: 'md',
        span: 2,
        ref: { resource: 'produtos_arvore_grupos', labelField: 'descricao_complex' },
        hint: 'Só o último nível da árvore (grupo sem subgrupos)',
      },
      {
        name: 'familia_grupo',
        label: 'Família / Grupo (texto)',
        type: 'text',
        searchable: true,
        filterable: true,
        sql: '(SELECT G.descricao_complex FROM produtos_arvore_grupos G WHERE G.ID = t.id_familia_grupo)',
      },
      { name: 'tipo_produto', label: 'Tipo', type: 'text', listed: true, filterable: true, width: 'sm', ref: { resource: 'produtos_tipos', labelField: 'descricao' } },
      { name: 'preco_venda', label: 'Preço Venda', type: 'decimal', scale: 3, listed: true, default: '0' },
      { name: 'custo_compra', label: 'Custo Compra', type: 'decimal', scale: 2, listed: true, default: '0' },
      { name: 'datahora_ultima_compra', label: 'Última compra em', type: 'datetime', listed: true },
      { name: 'id_fornec', label: 'Fornecedor', type: 'number', listed: true, width: 'md', ref: { resource: 'pessoas', labelField: 'nome' }, refFiltro: { campo: 'fornec_flag', valor: 'S' } },
      {
        name: 'estoque',
        label: 'Estoque',
        type: 'decimal',
        scale: 4,
        listed: true,
        // View produtos_estoque somada por grupo (o join do Delphi duplicava a linha com várias empresas)
        sql: '(SELECT SUM(E.QTDADE) FROM produtos_estoque E WHERE E.ID_PRODUTO = t.id AND E.ID_GRUPO = t.id_grupo)',
      },
      { name: 'id_marca_compatib', label: 'Marca Compatível', type: 'number', listed: true, width: 'sm', ref: { resource: 'produtos_marcas', labelField: 'descricao' } },
      { name: 'modelo_compatib', label: 'Modelos Compatíveis', type: 'text', listed: true, searchable: true, maxLength: 255, span: 2 },
    ],
  },
  simples('produtos_marcas', 'Marcas de produtos', 'Marca', 'Marcas dos produtos', 30),
  simples('produtos_familias', 'Famílias de produtos', 'Família', 'Famílias (1º nível da árvore de grupos)', 50),
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'produtos_grupos',
    table: 'produtos_grupos',
    label: 'Grupos de produtos',
    labelSingular: 'Grupo',
    description: 'Grupos e subgrupos de produtos (árvore Família > Grupo > Subgrupo)',
    icon: 'FolderTree',
    group: 'cadastros',
    oculto: true,
    labelField: 'descricao',
    defaultSort: { field: 'descricao', dir: 'asc' },
    fields: [
      ID,
      { name: 'descricao', label: 'Descrição', type: 'text', required: true, listed: true, searchable: true, maxLength: 50 },
      { name: 'id_familia', label: 'Família', type: 'number', listed: true, ref: { resource: 'produtos_familias', labelField: 'descricao' } },
      { name: 'id_produtos_grupos', label: 'Grupo pai', type: 'number', listed: true, default: 0, hint: '0 = grupo raiz da família' },
      { name: 'cor', label: 'Cor', type: 'text', maxLength: 10 },
    ],
  },
  {
    // View do banco (FAMÍLIA/GRUPO/SUBGRUPO): combo de Família/Grupo dos produtos, só com o último nível
    ...BASE,
    name: 'produtos_arvore_grupos',
    table: 'produtos_arvore_grupos',
    pk: ['ID'],
    autoIncrement: false,
    canCreate: false,
    canUpdate: false,
    canDelete: false,
    scopeSql: 't.ID_GRUPO = :grupo AND NOT EXISTS (SELECT 1 FROM produtos_grupos F WHERE F.id_produtos_grupos = t.ID)',
    label: 'Árvore de grupos',
    labelSingular: 'Grupo',
    description: 'Família/grupo/subgrupo (último nível)',
    icon: 'FolderTree',
    group: 'cadastros',
    oculto: true,
    labelField: 'descricao_complex',
    defaultSort: { field: 'descricao_complex', dir: 'asc' },
    fields: [
      { name: 'ID', label: 'Id', type: 'number', readOnly: true, listed: true },
      { name: 'descricao_complex', label: 'Família / Grupo', type: 'text', listed: true, searchable: true },
    ],
  },
  {
    // Lookup "Tipo" dos produtos (o Delphi não tem tela para eles)
    ...BASE,
    ...DO_GRUPO,
    name: 'produtos_tipos',
    table: 'produtos_tipos',
    autoIncrement: false,
    canCreate: false,
    canUpdate: false,
    canDelete: false,
    label: 'Tipos de produto',
    labelSingular: 'Tipo',
    description: 'Tipos de produto',
    icon: 'Tag',
    group: 'cadastros',
    oculto: true,
    labelField: 'descricao',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      { name: 'id', label: 'Id', type: 'text', listed: true, maxLength: 1 },
      { name: 'descricao', label: 'Descrição', type: 'text', listed: true, maxLength: 25 },
    ],
  },

  // ---------------------------------------------------------------- Tabelas
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'fatur_planos',
    table: 'fatur_planos',
    autoIncrement: false,
    label: 'Planos',
    labelSingular: 'Plano',
    description: 'Planos de cobrança (forma de cobrança do cliente)',
    icon: 'Receipt',
    group: 'tabelas',
    oculto: true,
    labelField: 'descricao',
    defaultSort: { field: 'descricao', dir: 'asc' },
    fields: [
      CODIGO,
      { name: 'descricao', label: 'Descrição', type: 'text', listed: true, searchable: true, maxLength: 25 },
      { name: 'modelo_nf', label: 'Modelo NF', type: 'text', listed: true, maxLength: 30 },
    ],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'fatur_series',
    table: 'fatur_series',
    autoIncrement: false,
    label: 'Séries',
    labelSingular: 'Série',
    description: 'Séries de nota da empresa ativa',
    icon: 'Hash',
    group: 'tabelas',
    oculto: true,
    labelField: 'descricao',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      CODIGO,
      { name: 'descricao', label: 'Descrição', type: 'text', listed: true, searchable: true, maxLength: 25 },
      { name: 'ultima_nota', label: 'Última NF', type: 'number', listed: true },
      { name: 'modelo_nf', label: 'Modelo NF', type: 'text', listed: true, maxLength: 30 },
    ],
  },
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'bancos',
    table: 'bancos',
    label: 'Bancos',
    labelSingular: 'Banco',
    description: 'Contas bancárias, dados do boleto e do CNAB',
    icon: 'Landmark',
    group: 'tabelas',
    oculto: true,
    labelField: 'apelido',
    defaultSort: { field: 'nome', dir: 'asc' },
    fields: [
      ID,
      { name: 'apelido', label: 'Apelido', type: 'text', required: true, listed: true, searchable: true, maxLength: 15, secao: 'Banco' },
      { name: 'nome', label: 'Nome', type: 'text', listed: true, searchable: true, maxLength: 30, span: 2, secao: 'Banco' },
      { name: 'cod_banco', label: 'Cód. banco', type: 'text', listed: true, maxLength: 3, width: 'xs', secao: 'Banco', hint: 'Número do banco na compensação (ex.: 341)' },
      { name: 'cod_banco_dig', label: 'Dig', type: 'text', maxLength: 1, secao: 'Banco' },
      sn('emite_boleto', 'Emite boleto', { listed: true, default: false, secao: 'Banco' }),
      { name: 'cod_agencia', label: 'Agência', type: 'text', listed: true, maxLength: 15, secao: 'Agência e conta' },
      { name: 'cod_agencia_dig', label: 'Dig', type: 'text', listed: true, maxLength: 3, width: 'xs', secao: 'Agência e conta' },
      { name: 'cod_conta', label: 'Conta', type: 'text', listed: true, maxLength: 15, secao: 'Agência e conta' },
      { name: 'cod_conta_dig', label: 'Dig', type: 'text', listed: true, maxLength: 3, width: 'xs', secao: 'Agência e conta' },
      { name: 'cod_cedente', label: 'Cód. Cedente', type: 'text', listed: true, maxLength: 15, secao: 'Cobrança' },
      { name: 'cod_cedente_dig', label: 'Dig', type: 'text', listed: true, maxLength: 3, width: 'xs', secao: 'Cobrança' },
      { name: 'cod_convenio', label: 'Convênio', type: 'text', listed: true, maxLength: 20, secao: 'Cobrança' },
      { name: 'cod_carteira', label: 'Cód. Carteira', type: 'text', listed: true, maxLength: 3, width: 'xs', secao: 'Cobrança' },
      { name: 'ultimo_nosso_numero', label: 'Último Nosso Nr.', type: 'number', listed: true, secao: 'Cobrança' },
      { name: 'ultima_remessa', label: 'Última remessa', type: 'number', default: 0, secao: 'Cobrança' },
      { name: 'codigos_remessa', label: 'Códigos de remessa (CNAB)', type: 'textarea', span: 4, secao: 'CNAB', hint: 'Uma linha chave=valor: variacao_carteira=027 (BB), codigo_transmissao=... (Santander; padrão agência + 0000 + cedente), nome_banco=...' },
      { name: 'codigos_retorno', label: 'Códigos de retorno (CNAB)', type: 'textarea', span: 4, secao: 'CNAB' },
      { name: 'codigos_retorno_erros', label: 'Códigos de erro do retorno (CNAB)', type: 'textarea', span: 4, secao: 'CNAB' },
    ],
  },
  {
    // Tabela global (IBGE, sem id_grupo): só consulta — no Delphi qualquer grupo alterava a tabela de todos
    ...BASE,
    name: 'cidades',
    table: 'cidades',
    canCreate: false,
    canUpdate: false,
    canDelete: false,
    label: 'Cidades',
    labelSingular: 'Cidade',
    description: 'Cidades do IBGE, faixa de CEP e UF',
    icon: 'MapPin',
    group: 'tabelas',
    oculto: true,
    labelField: 'nome',
    defaultSort: { field: 'uf', dir: 'asc' },
    fields: [
      { name: 'codigo', label: 'Cód. cidade', type: 'text', listed: true, searchable: true, maxLength: 7, width: 'sm' },
      { name: 'nome', label: 'Cidade', type: 'text', listed: true, searchable: true, filterable: true, maxLength: 28, width: 'lg' },
      { name: 'cep_ini', label: 'CEP início', type: 'text', listed: true, maxLength: 8, width: 'sm' },
      { name: 'cep_fim', label: 'CEP fim', type: 'text', listed: true, maxLength: 8, width: 'sm' },
      { name: 'uf', label: 'UF', type: 'enum', options: UFS, listed: true, filterable: true, width: 'xs' },
      { name: 'uf_codigo', label: 'Cód. UF', type: 'text', listed: true, maxLength: 2, width: 'xs' },
      { name: 'uf_nome', label: 'Estado', type: 'text', listed: true, maxLength: 18 },
    ],
  },

  // ---------------------------------------------------------------- Estoque (Kardex)
  {
    ...BASE,
    // Delphi: lista o grupo inteiro; o movimento novo leva a empresa ativa
    scopeSql: 't.id_grupo = :grupo',
    tenant: { grupo: 'id_grupo', empresa: 'id_empresa' },
    name: 'produtos_cardex',
    table: 'produtos_cardex',
    label: 'Movimento de estoque',
    labelSingular: 'Movimento',
    description: 'Kardex: entradas, saídas, saldo e custo médio por produto',
    icon: 'Boxes',
    group: 'movimento',
    oculto: true,
    labelField: 'documento',
    defaultSort: { field: 'datahora_mov', dir: 'desc' },
    fields: [
      ID,
      { name: 'ES', label: 'E/S', type: 'enum', required: true, listed: true, filterable: true, width: 'xs', options: opcoes([['E', 'Entrada'], ['S', 'Saída']]), default: 'E' },
      { name: 'produto_id', label: 'Produto', type: 'number', required: true, listed: true, filterable: true, width: 'lg', span: 2, ref: { resource: 'produtos', labelField: 'descricao' } },
      { name: 'documento', label: 'Documento', type: 'text', listed: true, searchable: true, maxLength: 15 },
      { name: 'data_mov', label: 'Data', type: 'date', required: true, listed: true, filterable: true },
      { name: 'hora_mov', label: 'Hora', type: 'time', listed: true },
      { name: 'qtdade_mov', label: 'Qtdade.', type: 'decimal', scale: 3, required: true, listed: true, default: '1' },
      { name: 'valor_total_mov', label: 'Vlr. Total', type: 'decimal', scale: 2, listed: true, default: '0', hint: 'Saídas: recalculado pelo custo médio em "Recalcular saldos"' },
      { name: 'valor_unit_mov', label: 'Vlr. Unit.', type: 'decimal', scale: 3, readOnly: true, listed: true },
      { name: 'qtdade_saldo', label: 'Saldo', type: 'decimal', scale: 3, readOnly: true, listed: true },
      { name: 'valor_total_estoque', label: 'Total Estoque', type: 'decimal', scale: 2, readOnly: true, listed: true },
      { name: 'valor_custo_medio_unit', label: 'Custo Médio', type: 'decimal', scale: 3, readOnly: true, listed: true },
      { name: 'obs', label: 'Obs.', type: 'text', maxLength: 80, span: 2 },
      { name: 'datahora_mov', label: 'Data/hora do movimento', type: 'datetime', readOnly: true },
      { name: 'datahora_inclusao', label: 'Inclusão', type: 'datetime', readOnly: true, listed: true },
      { name: 'usuario_inclusao', label: 'Usuário', type: 'number', readOnly: true, ref: { resource: 'usuarios', labelField: 'nome' } },
      { name: 'venda_id', label: 'Venda', type: 'number', readOnly: true },
      { name: 'compra_id', label: 'Compra', type: 'number', readOnly: true },
    ],
  },
];
