import type { FieldDef, ResourceDef } from '../schema.js';
import { BASE, DA_EMPRESA, ID, opcoes, sn } from './comum.js';

/**
 * Faturamento (fatur → fatur_notas → fatur_notas_produtos) e contas a receber de vendas (areceber).
 * As telas Faturamento e Financeiro são próprias (src/modulos/faturamento); estes metadados servem ao CRUD
 * genérico (consultas, grades de detalhe de outros módulos) com o mesmo escopo grupo + empresa.
 */
const dinheiro = (name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef => ({ name, label, type: 'decimal', scale: 2, ...extra });
const cliente: FieldDef = { name: 'id_cliente', label: 'Cliente', type: 'number', listed: true, filterable: true, ref: { resource: 'pessoas', labelField: 'nome' } };
const banco: FieldDef = { name: 'id_banco', label: 'Banco', type: 'number', listed: true, filterable: true, ref: { resource: 'bancos', labelField: 'apelido' } };
const boleto: FieldDef[] = [
  { name: 'boleto_nosso_numero', label: 'Boleto Nosso Nr.', type: 'text', readOnly: true, secao: 'Boleto' },
  { name: 'boleto_nosso_numero_dig', label: 'Boleto Dig', type: 'text', readOnly: true, width: 'xs', secao: 'Boleto' },
  { name: 'boleto_linha_digitavel', label: 'Boleto Linha Digitável', type: 'text', readOnly: true, span: 2, secao: 'Boleto' },
  { name: 'boleto_codigo_barras', label: 'Código de barras', type: 'text', readOnly: true, span: 2, secao: 'Boleto' },
];
const STATUS_NOTA = opcoes([
  ['A', 'A RECEBER'],
  ['R', 'RECEBIDO'],
  ['C', 'CANCELADO'],
]);
/** Escopo de tabela filha pelo pai (fatur_notas_produtos e fatur_financ não têm id_grupo/id_empresa) */
const filhoDe = (coluna: string, tabela: string) => ({ scopeSql: `t.${coluna} IN (SELECT x.id FROM ${tabela} x WHERE x.id_grupo = :grupo AND x.id_empresa = :empresa)` });

export const RECURSOS_FATURAMENTO: ResourceDef[] = [
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'fatur',
    table: 'fatur',
    label: 'Faturamentos',
    labelSingular: 'Faturamento',
    description: 'Lotes de faturamento das leituras de locação',
    icon: 'Receipt',
    group: 'movimento',
    oculto: true,
    canCreate: false,
    canDelete: false,
    labelField: 'obs',
    defaultSort: { field: 'data_fatur', dir: 'desc' },
    fields: [
      ID,
      { name: 'data_fatur', label: 'Data', type: 'date', readOnly: true, listed: true, filterable: true },
      { name: 'obs', label: 'Referência', type: 'text', listed: true, searchable: true, maxLength: 255, span: 2 },
      { name: 'id_usuario_inclusao', label: 'Usuário', type: 'number', readOnly: true, ref: { resource: 'usuarios', labelField: 'nome' } },
      { name: 'datahora_inclusao', label: 'Incluído em', type: 'datetime', readOnly: true },
    ],
    details: [{ resource: 'fatur_notas', foreignKey: 'id_fatur', label: 'Notas', totalField: 'total_liquido' }],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'fatur_notas',
    table: 'fatur_notas',
    label: 'Notas de débito / títulos a receber',
    labelSingular: 'Nota',
    description: 'Notas de débito de locação (títulos a receber, boletos, remessa e retorno)',
    icon: 'FileText',
    group: 'movimento',
    oculto: true,
    canCreate: false,
    labelField: 'numero',
    defaultSort: { field: 'data_vencimento', dir: 'asc' },
    fields: [
      ID,
      { name: 'id_fatur', label: 'Faturamento', type: 'number', readOnly: true, listed: true },
      cliente,
      { name: 'serie', label: 'Série', type: 'text', readOnly: true, listed: true, width: 'xs' },
      { name: 'numero', label: 'Nr. NF', type: 'number', readOnly: true, listed: true, searchable: true, width: 'sm' },
      { name: 'produto_descricao', label: 'Descrição', type: 'text', readOnly: true, span: 2 },
      { name: 'data_nota', label: 'Data NF', type: 'date', readOnly: true, listed: true, filterable: true },
      { name: 'data_vencimento', label: 'Data Vencto.', type: 'date', required: true, listed: true, filterable: true },
      dinheiro('total_bruto', 'Total bruto', { readOnly: true }),
      dinheiro('total_acrescimo', 'Acréscimo', { readOnly: true }),
      dinheiro('total_desconto', 'Desconto', { readOnly: true }),
      dinheiro('total_liquido', 'Total NF', { required: true, listed: true }),
      banco,
      { name: 'id_plano', label: 'Plano', type: 'text', listed: true, filterable: true, ref: { resource: 'fatur_planos', labelField: 'descricao' } },
      { name: 'status', label: 'Status', type: 'enum', readOnly: true, listed: true, filterable: true, options: STATUS_NOTA },
      sn('cancelado', 'Cancelado', { readOnly: true, filterable: true }),
      { name: 'status_email', label: 'e-Mail', type: 'enum', readOnly: true, options: opcoes([['E', 'ENVIADO'], ['N', 'NÃO ENVIADO']]) },
      { name: 'datahora_email', label: 'e-Mail enviado em', type: 'datetime', readOnly: true },
      sn('boleto_enviado', 'Remessa enviada', { readOnly: true, filterable: true }),
      ...boleto,
      dinheiro('total_recebido_principal', 'Recebido principal', { readOnly: true, secao: 'Baixa' }),
      dinheiro('total_recebido_juros', 'Juros', { readOnly: true, secao: 'Baixa' }),
      dinheiro('total_recebido_descontos', 'Descontos', { readOnly: true, secao: 'Baixa' }),
      dinheiro('total_recebido', 'Valor recebido', { readOnly: true, secao: 'Baixa' }),
      { name: 'data_baixa', label: 'Data Recbto.', type: 'date', readOnly: true, listed: true, secao: 'Baixa' },
      { name: 'datahora_baixa', label: 'Recebido em', type: 'datetime', readOnly: true, secao: 'Baixa' },
      { name: 'obs_baixa', label: 'Observação da baixa', type: 'text', readOnly: true, span: 2, secao: 'Baixa' },
      { name: 'tipo_baixa', label: 'Tipo de baixa', type: 'enum', readOnly: true, options: opcoes([['M', 'MANUAL'], ['A', 'AUTOMÁTICA (retorno)']]), secao: 'Baixa' },
      { name: 'ultima_ocorr_retorno', label: 'Última ocorrência', type: 'text', readOnly: true, secao: 'Retorno' },
      { name: 'ultima_obs_retorno', label: 'Obs. Retorno', type: 'text', readOnly: true, span: 2, secao: 'Retorno' },
      { name: 'arquivo_retorno', label: 'Arquivo de retorno', type: 'text', readOnly: true, secao: 'Retorno' },
    ],
    details: [{ resource: 'fatur_notas_produtos', foreignKey: 'id_nota', label: 'Produtos da Nota', totalField: 'valor_liquido' }],
  },
  {
    ...BASE,
    ...filhoDe('id_nota', 'fatur_notas'),
    name: 'fatur_notas_produtos',
    table: 'fatur_notas_produtos',
    label: 'Produtos da nota',
    labelSingular: 'Produto da nota',
    description: 'Leituras faturadas em cada nota',
    icon: 'Printer',
    group: 'movimento',
    oculto: true,
    canCreate: false,
    canUpdate: false,
    canDelete: false,
    labelField: 'descricao',
    defaultSort: { field: 'id_equip', dir: 'asc' },
    fields: [
      ID,
      { name: 'id_nota', label: 'Nota', type: 'number', readOnly: true },
      { name: 'id_contrato', label: 'Contrato', type: 'number', readOnly: true },
      { name: 'id_equip', label: 'ID', type: 'number', readOnly: true, listed: true, width: 'xs' },
      { name: 'descricao', label: 'Equipamento', type: 'text', readOnly: true, listed: true },
      { name: 'nr_serie', label: 'Série', type: 'text', readOnly: true, listed: true, sql: '(SELECT e.nr_serie FROM equipamentos e WHERE e.id = t.id_equip)' },
      { name: 'setor', label: 'Setor', type: 'text', readOnly: true, listed: true },
      { name: 'leitura_anterior', label: 'Leitura Anterior', type: 'number', readOnly: true, listed: true },
      { name: 'leitura_atual', label: 'Leitura Atual', type: 'number', readOnly: true, listed: true },
      { name: 'nr_copias', label: 'Nr. Cópias', type: 'number', readOnly: true, listed: true },
      { name: 'nr_copias_contrato', label: 'Nr. Cópias Contrato', type: 'number', readOnly: true, listed: true },
      { name: 'nr_copias_exced', label: 'Nr. Cópias Exced.', type: 'number', readOnly: true, listed: true },
      { name: 'valor_unit_copia', label: 'Vlr. Unit Cópia', type: 'decimal', scale: 5, readOnly: true, listed: true },
      { name: 'valor_unit_exced', label: 'Vlr. Unit Exced.', type: 'decimal', scale: 5, readOnly: true, listed: true },
      dinheiro('valor_total_contrato', 'Vlr. Total Contrato', { readOnly: true, listed: true }),
      dinheiro('valor_total_exced', 'Vlr. Total Exced.', { readOnly: true, listed: true }),
      dinheiro('valor_bruto', 'Valor bruto', { readOnly: true }),
      dinheiro('valor_acrescimo', 'Acréscimo', { readOnly: true }),
      dinheiro('valor_desconto', 'Desconto', { readOnly: true }),
      dinheiro('valor_liquido', 'Valor NF', { readOnly: true, listed: true }),
      { name: 'obs', label: 'Observação', type: 'text', readOnly: true },
      sn('cancelado', 'Cancelado', { readOnly: true }),
    ],
  },
  {
    // Existe no banco mas o Delphi não grava (juntar_financ sem efeito): só consulta
    ...BASE,
    ...filhoDe('id_fatur', 'fatur'),
    name: 'fatur_financ',
    table: 'fatur_financ',
    label: 'Financeiro do faturamento',
    labelSingular: 'Parcela',
    description: 'Financeiro separado do faturamento (não usado pelo sistema)',
    icon: 'Wallet',
    group: 'movimento',
    oculto: true,
    canCreate: false,
    canUpdate: false,
    canDelete: false,
    labelField: 'id',
    defaultSort: { field: 'data_vencimento', dir: 'asc' },
    fields: [
      ID,
      { name: 'id_fatur', label: 'Faturamento', type: 'number', readOnly: true, listed: true },
      cliente,
      banco,
      { name: 'data_geracao', label: 'Geração', type: 'date', readOnly: true, listed: true },
      { name: 'data_vencimento', label: 'Vencimento', type: 'date', readOnly: true, listed: true },
      dinheiro('valor', 'Valor', { readOnly: true, listed: true }),
      { name: 'status', label: 'Status', type: 'enum', readOnly: true, listed: true, options: STATUS_NOTA },
      ...boleto,
      sn('boleto_enviado', 'Remessa enviada', { readOnly: true }),
    ],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'areceber',
    table: 'areceber',
    label: 'Contas a receber (vendas)',
    labelSingular: 'Parcela a receber',
    description: 'Parcelas a receber das vendas (boletos pela tela Geração / Impressão Boleto)',
    icon: 'Wallet',
    group: 'movimento',
    oculto: true,
    labelField: 'documento',
    defaultSort: { field: 'data_vencimento', dir: 'asc' },
    fields: [
      ID,
      { name: 'id_venda', label: 'Venda', type: 'number', listed: true, filterable: true },
      cliente,
      banco,
      { name: 'tipo_operacao', label: 'Operação', type: 'text', maxLength: 3, width: 'xs' },
      { name: 'documento', label: 'Documento', type: 'text', listed: true, searchable: true, maxLength: 20 },
      { name: 'parcelas_nr', label: 'Parcela', type: 'number', listed: true, width: 'xs' },
      { name: 'parcelas_tot', label: 'De', type: 'number', width: 'xs' },
      { name: 'data_venda', label: 'Data venda', type: 'date', listed: true },
      { name: 'data_vencimento', label: 'Vencimento', type: 'date', required: true, listed: true, filterable: true },
      { name: 'data_recebimento', label: 'Recebimento', type: 'date' },
      { name: 'data_ultimo_recebimento', label: 'Último recebimento', type: 'date', readOnly: true },
      dinheiro('valor_original', 'Valor original'),
      dinheiro('valor_areceber', 'Valor a receber', { required: true, listed: true }),
      dinheiro('valor_ja_recebido', 'Já recebido', { readOnly: true, listed: true }),
      { name: 'multa_perc', label: 'Multa %', type: 'decimal', scale: 3 },
      { name: 'juros_perc_mes', label: 'Juros % mês', type: 'decimal', scale: 3 },
      { name: 'juros_valor_dia', label: 'Juros R$ dia', type: 'decimal', scale: 3 },
      { name: 'desconto_perc_mes', label: 'Desconto % mês', type: 'decimal', scale: 3 },
      { name: 'desconto_valor_dia', label: 'Desconto R$ dia', type: 'decimal', scale: 3 },
      dinheiro('outros_acrescimos_valor', 'Outros acréscimos'),
      dinheiro('outros_descontos_valor', 'Outros descontos'),
      ...boleto,
      sn('boleto_enviado', 'Remessa enviada', { readOnly: true }),
      { name: 'obs1', label: 'Obs. 1', type: 'text', maxLength: 255, span: 2, secao: 'Observações' },
      { name: 'obs2', label: 'Obs. 2', type: 'text', maxLength: 255, span: 2, secao: 'Observações' },
      { name: 'obs3', label: 'Obs. 3', type: 'text', maxLength: 255, span: 2, secao: 'Observações' },
      { name: 'obs4', label: 'Obs. 4', type: 'text', maxLength: 255, span: 2, secao: 'Observações' },
      { name: 'obs5', label: 'Obs. 5', type: 'text', maxLength: 255, span: 2, secao: 'Observações' },
      { name: 'status', label: 'Status', type: 'text', listed: true, filterable: true, maxLength: 1, width: 'xs' },
      sn('visto_caixa', 'Visto caixa'),
    ],
    details: [{ resource: 'areceber_baixas', foreignKey: 'id_areceber', label: 'Baixas', totalField: 'valor_total_recebido' }],
  },
  {
    ...BASE,
    ...filhoDe('id_areceber', 'areceber'),
    name: 'areceber_baixas',
    table: 'areceber_baixas',
    label: 'Baixas de contas a receber',
    labelSingular: 'Baixa',
    description: 'Recebimentos das parcelas de venda',
    icon: 'Banknote',
    group: 'movimento',
    oculto: true,
    labelField: 'id',
    defaultSort: { field: 'data_recto', dir: 'desc' },
    fields: [
      ID,
      { name: 'id_areceber', label: 'Parcela', type: 'number', required: true, listed: true },
      { name: 'data_recto', label: 'Recebimento', type: 'date', required: true, listed: true },
      { name: 'data_vencimento', label: 'Vencimento', type: 'date', listed: true },
      dinheiro('valor_areceber', 'A receber', { listed: true }),
      dinheiro('valor_recebido', 'Recebido'),
      { name: 'valor_multa', label: 'Multa', type: 'decimal', scale: 3 },
      { name: 'valor_juros', label: 'Juros', type: 'decimal', scale: 3 },
      dinheiro('valor_outros_acrescimos', 'Outros acréscimos'),
      dinheiro('valor_descontos', 'Descontos'),
      dinheiro('valor_descontos_vales', 'Descontos vales'),
      dinheiro('valor_total_recebido', 'Total recebido', { listed: true }),
      dinheiro('valor_dinheiro', 'Dinheiro', { secao: 'Formas' }),
      dinheiro('valor_cheque', 'Cheque', { secao: 'Formas' }),
      dinheiro('valor_cartao', 'Cartão', { secao: 'Formas' }),
      dinheiro('valor_vales', 'Vales', { secao: 'Formas' }),
      dinheiro('valor_outros', 'Outros', { secao: 'Formas' }),
      dinheiro('juros_sobra', 'Juros sobra'),
      { name: 'tipo_rec', label: 'Tipo', type: 'text', maxLength: 1, width: 'xs' },
      { name: 'id_usuario', label: 'Usuário', type: 'number', readOnly: true, ref: { resource: 'usuarios', labelField: 'nome' } },
      { name: 'datahora_registro', label: 'Registrado em', type: 'datetime', readOnly: true },
      { name: 'obs', label: 'Observação', type: 'text', maxLength: 255, span: 2 },
    ],
  },
];
