import type { ResourceDef } from '../schema.js';
import { BASE, DA_EMPRESA, DO_GRUPO, ID, opcoes, sn } from './comum.js';

/** Leituras e conferências não têm grupo/empresa: valem as do contrato da empresa ativa */
const DO_CONTRATO = { scopeSql: 't.id_contrato IN (SELECT c.id FROM locacao_contratos c WHERE c.id_grupo = :grupo AND c.id_empresa = :empresa)' };

/**
 * Locações (ufrmContratos do Delphi, nível A). A tela é própria (src/modulos/locacoes.tsx); estes metadados
 * servem o formulário genérico e as gravações pelo CRUD (regras em server/locacoes.ts).
 */
export const RECURSOS_LOCACOES: ResourceDef[] = [
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'locacao_contratos',
    table: 'locacao_contratos',
    label: 'Contratos de locação',
    labelSingular: 'Contrato',
    description: 'Contratos de locação: equipamento, contador (P&B/cor), franquia e preços',
    icon: 'FileSignature',
    group: 'locacoes',
    oculto: true,
    labelField: 'nr_serie',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      { ...ID, label: 'ID/Contrato' },
      { name: 'id_cliente', label: 'Cliente', type: 'number', required: true, listed: true, span: 2, ref: { resource: 'pessoas', labelField: 'nome' } },
      { name: 'id_equip', label: 'Equipamento (nr. série)', type: 'number', required: true, listed: true, span: 2, ref: { resource: 'equipamentos', labelField: 'nr_serie' } },
      { name: 'nr_serie', label: 'Nr. série', type: 'text', readOnly: true, searchable: true },
      sn('color', 'Colorido', { listed: true, hint: 'Contador cobrado: colorido (ligado) ou P&B. Multifuncional cobrada nos dois = 2 contratos' }),
      { name: 'rede_usb', label: 'Rede/USB', type: 'enum', required: true, options: opcoes([['R', 'REDE'], ['U', 'USB']]), default: 'R' },
      { name: 'id_vendedor', label: 'Vendedor', type: 'number', ref: { resource: 'vendedores', labelField: 'nome' } },
      { name: 'codigo_grupo', label: 'Grupo', type: 'text', maxLength: 5, hint: 'Contratos do mesmo grupo compartilham franquia/mínimo' },
      { name: 'setor', label: 'Setor', type: 'text', maxLength: 60, span: 2 },
      { name: 'dia_leitura', label: 'Dia leitura', type: 'number', required: true },
      { name: 'dia_vencimento', label: 'Dia vencto.', type: 'number', required: true },
      { name: 'nr_copias', label: 'Nr. cópias (franquia)', type: 'number', default: 0, hint: '0 = LIVRE (cobra por cópia)' },
      { name: 'valor_contrato', label: 'Valor locação R$', type: 'decimal', scale: 2, default: '0', hint: 'Livre: vale como valor mínimo no agrupamento' },
      { name: 'valor_copia', label: 'Valor cópia R$', type: 'decimal', scale: 5, default: '0', hint: 'Com franquia é calculado (valor ÷ cópias)' },
      { name: 'valor_excedente', label: 'Valor excedente R$', type: 'decimal', scale: 5, default: '0', hint: 'Em branco/zero = valor da cópia' },
      { name: 'data_contrato', label: 'Data contrato', type: 'date' },
      { name: 'data_vencimento', label: 'Validade', type: 'date' },
      { name: 'serie_nf', label: 'Série / NF', type: 'text', required: true, ref: { resource: 'fatur_series', labelField: 'descricao' } },
      { name: 'obs', label: 'Observações', type: 'text', maxLength: 255, span: 4 },
      sn('ativo', 'Ativo', { listed: true, default: true }),
      sn('juntar_nota', 'Juntar NF', { default: true }),
      sn('juntar_financ', 'Juntar financeiro', { default: true }),
    ],
    details: [{ resource: 'locacao_leituras', foreignKey: 'id_contrato', label: 'Leituras', totalField: 'valor_total_geral', editavel: true }],
  },
  {
    ...BASE,
    ...DO_CONTRATO,
    name: 'locacao_leituras',
    table: 'locacao_leituras',
    label: 'Leituras',
    labelSingular: 'Leitura',
    description: 'Leituras mensais dos contratos (contadores, franquia, excedente e total)',
    icon: 'Gauge',
    group: 'locacoes',
    oculto: true,
    labelField: 'data_leitura',
    defaultSort: { field: 'data_leitura', dir: 'desc' },
    fields: [
      ID,
      { name: 'id_contrato', label: 'Contrato', type: 'number', required: true },
      sn('status_fatur', 'Faturado', { listed: true }),
      { name: 'data_leitura', label: 'Data leitura', type: 'date', required: true, listed: true },
      { name: 'data_vencimento', label: 'Data vencto.', type: 'date', listed: true },
      { name: 'leitura_anterior', label: 'Leitura anterior', type: 'number', listed: true },
      { name: 'leitura_atual', label: 'Leitura atual', type: 'number', listed: true },
      { name: 'valor_total_geral', label: 'Total R$', type: 'decimal', scale: 2, readOnly: true, listed: true },
      { name: 'nr_copias_mes', label: 'Nr. cópias (mês)', type: 'number', readOnly: true, listed: true },
      { name: 'nr_copias_total', label: 'Nr. cópias (total)', type: 'number', listed: true, hint: 'Zero = calculado (total anterior + mês)' },
      { name: 'nr_copias_contrato', label: 'Nr. cópias (contrato)', type: 'number', readOnly: true, listed: true },
      { name: 'nr_copias_excedente', label: 'Nr. cópias (exced.)', type: 'number', listed: true, hint: 'Pode ser corrigido à mão quando a leitura não passou da franquia' },
      { name: 'nd', label: 'ND', type: 'number', listed: true },
      { name: 'valor_copia_unit', label: 'Valor unit. R$', type: 'decimal', scale: 5, readOnly: true, listed: true },
      { name: 'valor_copia_total', label: 'Valor total R$', type: 'decimal', scale: 2, readOnly: true, listed: true },
      { name: 'valor_copia_unit_excedente', label: 'Valor unit. (exced.)', type: 'decimal', scale: 5, readOnly: true, listed: true },
      { name: 'valor_copia_total_excedente', label: 'Valor total (exced.)', type: 'decimal', scale: 2, readOnly: true, listed: true },
      { name: 'obs', label: 'Observações', type: 'text', maxLength: 255, span: 4, listed: true },
      { name: 'nr_serie', label: 'Nr. série', type: 'text', readOnly: true },
      { name: 'color', label: 'Color', type: 'text', readOnly: true },
      { name: 'codigo_grupo', label: 'Grupo', type: 'text', readOnly: true },
      { name: 'grupo_acertado', label: 'Acertado', type: 'text', readOnly: true },
      { name: 'nr_copiar_total_anterior', label: 'Total anterior', type: 'number', readOnly: true },
      { name: 'valor_contrato', label: 'Valor contrato', type: 'decimal', scale: 2, readOnly: true },
    ],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'locacao_pre_leituras',
    table: 'locacao_pre_leituras',
    label: 'Pré-leituras',
    labelSingular: 'Lote de pré-leituras',
    description: 'Lotes de contratos a ler (gerados pela aba Pré-Leituras)',
    icon: 'ListChecks',
    group: 'locacoes',
    oculto: true,
    canCreate: false,
    canUpdate: false,
    canDelete: false,
    labelField: 'datahora_geracao',
    defaultSort: { field: 'datahora_geracao', dir: 'desc' },
    fields: [
      ID,
      { name: 'datahora_geracao', label: 'Gerado em', type: 'datetime', readOnly: true, listed: true },
      { name: 'filtro_dia_leitura', label: 'Dia leitura', type: 'text', readOnly: true, listed: true },
      { name: 'filtro_ate_data', label: 'Até', type: 'date', readOnly: true, listed: true },
      { name: 'filtro_cliente', label: 'Cliente', type: 'text', readOnly: true, listed: true },
    ],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'locacao_pre_leituras_leituras',
    table: 'locacao_pre_leituras_leituras',
    label: 'Itens da pré-leitura',
    labelSingular: 'Pré-leitura',
    description: 'Contratos de um lote de pré-leituras com os contadores capturados',
    icon: 'ListChecks',
    group: 'locacoes',
    oculto: true,
    canCreate: false,
    labelField: 'nr_serie',
    defaultSort: { field: 'nome', dir: 'asc' },
    fields: [
      ID,
      { name: 'id_leitura', label: 'Lote', type: 'number', readOnly: true },
      { name: 'faturar', label: 'Conferido', type: 'enum', options: opcoes([['S', 'SIM'], ['N', 'NÃO'], ['F', 'FATURADO']]), listed: true },
      { name: 'status', label: 'Status', type: 'enum', readOnly: true, listed: true, options: opcoes([['G', 'GERADO'], ['C', 'CAPTURADO'], ['P', 'A FATURAR'], ['F', 'FATURADO'], ['Z', 'ZERADO']]) },
      { name: 'nr_serie', label: 'Nr. série', type: 'text', readOnly: true, listed: true },
      { name: 'rede_usb', label: 'Rede/USB', type: 'enum', options: opcoes([['R', 'REDE'], ['U', 'USB']]), listed: true },
      { name: 'leitura_pb_anterior', label: 'P&B anterior', type: 'number', listed: true },
      { name: 'leitura_pb', label: 'P&B atual', type: 'number', listed: true },
      { name: 'leitura_color_anterior', label: 'Color anterior', type: 'number', listed: true },
      { name: 'leitura_color', label: 'Color atual', type: 'number', listed: true },
      { name: 'data_leitura_prevista', label: 'Previsão', type: 'date', readOnly: true },
      { name: 'datahora_leitura_auto', label: 'Última captura', type: 'datetime', readOnly: true },
      { name: 'nome', label: 'Cliente', type: 'text', readOnly: true },
    ],
  },
  {
    ...BASE,
    ...DO_CONTRATO,
    name: 'locacao_confere',
    table: 'locacao_confere',
    label: 'Conferência de leituras',
    labelSingular: 'Conferência',
    description: 'Contratos marcados como conferidos na Conferência de Leituras',
    icon: 'CheckCheck',
    group: 'locacoes',
    oculto: true,
    canCreate: false,
    canUpdate: false,
    canDelete: false,
    labelField: 'data_vencimento',
    defaultSort: { field: 'id', dir: 'desc' },
    fields: [
      ID,
      { name: 'id_contrato', label: 'Contrato', type: 'number', readOnly: true, listed: true },
      { name: 'dia_leitura', label: 'Dia leitura', type: 'number', readOnly: true, listed: true },
      { name: 'data_vencimento', label: 'Vencimento', type: 'date', readOnly: true, listed: true },
    ],
  },
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'vendedores',
    table: 'vendedores',
    label: 'Vendedores',
    labelSingular: 'Vendedor',
    description: 'Vendedores dos contratos de locação',
    icon: 'BadgeDollarSign',
    group: 'locacoes',
    oculto: true,
    labelField: 'nome',
    defaultSort: { field: 'nome', dir: 'asc' },
    fields: [
      ID,
      { name: 'nome', label: 'Nome', type: 'text', required: true, listed: true, searchable: true, maxLength: 50, span: 4 },
    ],
  },
];
