import type { FieldDef, ResourceDef } from '../schema.js';
import { BASE, DA_EMPRESA, DO_GRUPO, ID, opcoes, sn } from './comum.js';

/** Peças e produtos ficam ligados à OS/requisição: o escopo vem do mestre (no Delphi as peças gravavam grupo/empresa NULL) */
const PELO_MESTRE = (mestre: string, chave: string) => ({
  scopeSql: `t.${chave} IN (SELECT m.id FROM ${mestre} m WHERE m.id_grupo = :grupo AND m.id_empresa = :empresa)`,
  tenant: { grupo: 'id_grupo', empresa: 'id_empresa' },
});

const STATUS_OS = opcoes([['A', 'ABERTO'], ['E', 'EXECUTANDO'], ['F', 'FECHADO']]);
const STATUS_REQ = opcoes([['A', 'PENDENTE'], ['I', 'ENTREGANDO'], ['E', 'ENTREGUE']]);
const valor = (name: string, label: string): FieldDef => ({ name, label, type: 'decimal', scale: 2, listed: false, secao: 'Valores' });
const cliente: FieldDef = { name: 'id_cliente', label: 'Cliente', type: 'number', listed: true, filterable: true, ref: { resource: 'pessoas', labelField: 'nome' } };
const equip: FieldDef = { name: 'id_equip', label: 'Equipamento', type: 'number', ref: { resource: 'equipamentos', labelField: 'descricao' } };
const produto: FieldDef = { name: 'id_produto', label: 'Produto', type: 'number', listed: true, ref: { resource: 'produtos', labelField: 'descricao' } };

/**
 * Ordens de Serviço, Requisições e Consultas (ufrmOS, ufrmRequisicoes, ufrmConsultas).
 * As telas são próprias (src/modulos/os.tsx) e leem as listas por rotas de server/os.ts (com os JOINs do Delphi);
 * as gravações passam pelo CRUD genérico destes recursos, com as regras de server/os.ts.
 */
export const RECURSOS_OS: ResourceDef[] = [
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'os',
    table: 'os',
    label: 'Ordens de Serviço',
    labelSingular: 'OS',
    description: 'Ordens de serviço da empresa, peças e pedidos dos clientes',
    icon: 'Wrench',
    group: 'operacao',
    nivel: 'T',
    labelField: 'id',
    defaultSort: { field: 'id', dir: 'asc' },
    details: [{ resource: 'os_pecas', foreignKey: 'id_os', label: 'Peças / Produtos / Serviços', totalField: 'valor_total', editavel: true }],
    fields: [
      ID,
      { name: 'status', label: 'Status', type: 'enum', options: STATUS_OS, listed: true, filterable: true, readOnly: true },
      sn('status_impressao', 'Impresso', { listed: true, readOnly: true }),
      { name: 'datahora_inclusao', label: 'Incluído em', type: 'datetime', listed: true, readOnly: true },
      { name: 'os_tipo', label: 'Tipo', type: 'text', listed: true, filterable: true, required: true, default: 'C', ref: { resource: 'os_tipos', labelField: 'descricao' } },
      cliente,
      { name: 'id_contrato', label: 'Contrato', type: 'number' },
      equip,
      { name: 'equip_descricao', label: 'Equipamento (descrição)', type: 'text', maxLength: 50, readOnly: true },
      { name: 'id_produto', label: 'Produto', type: 'number', readOnly: true },
      { name: 'id_os_cliente', label: 'Pedido do cliente', type: 'number', readOnly: true },
      { name: 'cnpj_cliente', label: 'CNPJ do cliente', type: 'text', maxLength: 14 },
      { name: 'obs', label: 'Observação', type: 'text', maxLength: 255, listed: true, searchable: true, span: 2 },
      { name: 'nome_req', label: 'Requisitado por', type: 'text', maxLength: 50, listed: true, searchable: true },
      { name: 'data_os', label: 'Data OS', type: 'date', listed: true },
      { name: 'qtdade_os', label: 'Qtd. solicitada', type: 'decimal', scale: 2, readOnly: true },
      { name: 'data_execucao', label: 'Execução', type: 'date', listed: true },
      { name: 'qtdade_usada', label: 'Qtd. usada', type: 'decimal', scale: 2, readOnly: true },
      { name: 'defeito_cliente', label: 'Relatado pelo cliente', type: 'textarea', maxLength: 255, searchable: true, span: 4 },
      { name: 'defeito_constatado', label: 'Constatado', type: 'textarea', maxLength: 255, span: 4 },
      { name: 'servico_realizado', label: 'Serviço realizado', type: 'textarea', maxLength: 255, span: 4 },
      { name: 'obs_interna', label: 'Observação interna', type: 'textarea', maxLength: 255, span: 4 },
      { name: 'id_usuario_inclusao', label: 'Incluído por', type: 'number', readOnly: true, ref: { resource: 'usuarios', labelField: 'nome' } },
      valor('valor_servicos', 'Vlr. Serviços'),
      valor('valor_pecas', 'Vlr. Peças'),
      valor('valor_terceiros', 'Vlr. Terceiros'),
      valor('valor_total_bruto', 'Total Bruto'),
      valor('valor_acrescimos', '+ Acresc.'),
      valor('valor_descontos', '- Desc.'),
      valor('valor_total_liquido', 'Total Líquido'),
    ],
  },
  {
    ...BASE,
    ...PELO_MESTRE('os', 'id_os'),
    name: 'os_pecas',
    table: 'os_pecas',
    label: 'Peças da OS',
    labelSingular: 'Peça',
    description: 'Peças, produtos e serviços da OS',
    icon: 'Package',
    group: 'operacao',
    nivel: 'T',
    oculto: true,
    labelField: 'id',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      { name: 'id_os', label: 'OS', type: 'number', required: true },
      produto,
      { name: 'qtdade', label: 'Qtd.', type: 'decimal', scale: 2, listed: true, required: true },
      { name: 'qtdade_entregue', label: 'Qtd. Entregue', type: 'decimal', scale: 2, listed: true },
      { name: 'valor_unit', label: 'Vlr. Unit.', type: 'decimal', scale: 4, listed: true },
      { name: 'valor_total', label: 'Vlr. Total', type: 'decimal', scale: 2, listed: true, readOnly: true },
      { name: 'obs', label: 'Observação', type: 'text', maxLength: 255, listed: true, span: 2 },
      { name: 'nr_serie', label: 'Nr. Série', type: 'text', maxLength: 25, listed: true },
    ],
  },
  {
    ...BASE,
    name: 'os_tipos',
    table: 'os_tipos',
    label: 'Tipos de OS',
    labelSingular: 'Tipo de OS',
    description: 'C=Contrato, D=Devolução, E=Entrega, F=Faturado, G=Recarga, R=Requisição, S=Serviço',
    icon: 'Tags',
    group: 'operacao',
    oculto: true,
    autoIncrement: false,
    labelField: 'descricao',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      { name: 'id', label: 'Letra', type: 'text', required: true, listed: true, maxLength: 1, width: 'xs' },
      { name: 'descricao', label: 'Descrição', type: 'text', required: true, listed: true, maxLength: 25 },
    ],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'os_cliente',
    table: 'os_cliente',
    label: 'OS solicitadas pelos clientes',
    labelSingular: 'Pedido de OS',
    description: 'Pedidos de OS feitos na Área do Cliente (A = pendente, R = requisitado)',
    icon: 'Inbox',
    group: 'operacao',
    nivel: 'T',
    oculto: true,
    canCreate: false,
    labelField: 'id',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      cliente,
      { name: 'id_contrato', label: 'Contrato', type: 'number' },
      equip,
      { name: 'equip_descricao', label: 'Equipamento', type: 'text', maxLength: 50, listed: true },
      { name: 'tipo_os', label: 'Tipo OS', type: 'enum', options: opcoes([['R', 'Req. Cartucho'], ['C', 'Serviço']]), listed: true },
      { name: 'qtdade', label: 'Qtd. Cart.', type: 'decimal', scale: 2, listed: true },
      { name: 'qtdade_cil', label: 'Qtd. Cil.', type: 'decimal', scale: 2, listed: true },
      { name: 'cnpj_cliente', label: 'CNPJ', type: 'text', maxLength: 14 },
      { name: 'nome_req', label: 'Requisitado por', type: 'text', maxLength: 50, listed: true },
      { name: 'datahora_os', label: 'Incluído em', type: 'datetime', listed: true },
      { name: 'datahora_status', label: 'Data do status', type: 'datetime' },
      { name: 'status', label: 'Status', type: 'enum', options: opcoes([['A', 'Pendente'], ['R', 'Requisitado']]), listed: true },
      { name: 'obs', label: 'Observação', type: 'text', maxLength: 255, listed: true },
      { name: 'nota_avaliacao', label: 'Nota', type: 'number' },
      { name: 'obs_avaliacao', label: 'Comentário da avaliação', type: 'text', maxLength: 255 },
    ],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'req',
    table: 'req',
    label: 'Requisições',
    labelSingular: 'Requisição',
    description: 'Requisições de material dos clientes',
    icon: 'ClipboardList',
    group: 'operacao',
    labelField: 'id',
    defaultSort: { field: 'id', dir: 'asc' },
    details: [{ resource: 'req_produtos', foreignKey: 'id_req', label: 'Produtos', editavel: true }],
    fields: [
      ID,
      { name: 'status', label: 'Status', type: 'enum', options: STATUS_REQ, listed: true, filterable: true, default: 'A' },
      sn('status_impressao', 'Impresso', { listed: true, readOnly: true }),
      { name: 'data_req', label: 'Requisitado em', type: 'date', listed: true },
      { name: 'data_entrega', label: 'Entrega', type: 'date', listed: true },
      cliente,
      { name: 'obs', label: 'Observação', type: 'text', maxLength: 255, listed: true, span: 2 },
      { name: 'id_usuario_inclusao', label: 'Incluído por', type: 'number', readOnly: true, ref: { resource: 'usuarios', labelField: 'nome' } },
      { name: 'datahora_inclusao', label: 'Incluído em', type: 'datetime', readOnly: true, listed: true },
    ],
  },
  {
    ...BASE,
    ...PELO_MESTRE('req', 'id_req'),
    name: 'req_produtos',
    table: 'req_produtos',
    label: 'Produtos da requisição',
    labelSingular: 'Produto',
    description: 'Produtos requisitados',
    icon: 'Package',
    group: 'operacao',
    oculto: true,
    labelField: 'id',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      { name: 'id_req', label: 'Requisição', type: 'number', required: true },
      { name: 'id_cliente', label: 'Cliente', type: 'number', readOnly: true },
      { name: 'id_contrato', label: 'Contrato', type: 'number' },
      { ...equip, listed: true, readOnly: true },
      { name: 'equip_descricao', label: 'Equipamento (descrição)', type: 'text', maxLength: 50, readOnly: true },
      produto,
      { name: 'id_req_cliente', label: 'Pedido do cliente', type: 'number', readOnly: true },
      { name: 'cnpj_cliente', label: 'CNPJ', type: 'text', maxLength: 14 },
      { name: 'qtdade_req', label: 'Qtd. Req.', type: 'decimal', scale: 2, listed: true, required: true },
      { name: 'nome_req', label: 'Requisitado por', type: 'text', maxLength: 50, listed: true },
      { name: 'datahora_req', label: 'Requisitado em', type: 'datetime', listed: true },
      { name: 'datahora_entrega', label: 'Entregue em', type: 'datetime', listed: true },
      { name: 'qtdade_entregue', label: 'Qtd. Entregue', type: 'decimal', scale: 2, listed: true },
      { name: 'obs', label: 'Observação', type: 'text', maxLength: 255, listed: true, span: 2 },
    ],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    name: 'req_cliente',
    table: 'req_cliente',
    label: 'Requisições dos clientes',
    labelSingular: 'Pedido de requisição',
    description: 'Pedidos de cartucho feitos pelos clientes (A = pendente, R = requisitado)',
    icon: 'Inbox',
    group: 'operacao',
    oculto: true,
    canCreate: false,
    labelField: 'id',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      cliente,
      { name: 'id_contrato', label: 'Contrato', type: 'number' },
      equip,
      produto,
      { name: 'equip_descricao', label: 'Impressora', type: 'text', maxLength: 50, listed: true },
      { name: 'cnpj_cliente', label: 'CNPJ', type: 'text', maxLength: 14 },
      { name: 'nome_req', label: 'Requerente', type: 'text', maxLength: 50, listed: true },
      { name: 'datahora_req', label: 'Requisitado em', type: 'datetime', listed: true },
      { name: 'qtdade_req', label: 'Qtdade.', type: 'decimal', scale: 2, listed: true },
      { name: 'obs', label: 'Observação', type: 'text', maxLength: 255, listed: true },
      { name: 'status', label: 'Status', type: 'enum', options: opcoes([['A', 'Pendente'], ['R', 'Requisitado']]), listed: true },
      { name: 'nota_avaliacao', label: 'Nota', type: 'number' },
    ],
  },
  {
    // Cadastro das consultas: só administradores (o SQL é livre). A execução (nível T) é pelas rotas de server/os.ts
    ...BASE,
    ...DO_GRUPO,
    name: 'consultas',
    table: 'consultas',
    label: 'Cadastro de consultas',
    labelSingular: 'Consulta',
    description: 'SQLs das consultas configuráveis, parâmetros, títulos e permissões',
    icon: 'BarChart3',
    group: 'operacao',
    oculto: true,
    labelField: 'descricao_resumida',
    defaultSort: { field: 'grupo', dir: 'asc' },
    ficha: true,
    fields: [
      ID,
      { name: 'grupo', label: 'Grupo', type: 'text', maxLength: 25, listed: true, searchable: true, filterable: true, secao: 'Consulta' },
      { name: 'codigo', label: 'Código', type: 'text', maxLength: 15, listed: true, searchable: true, secao: 'Consulta' },
      { name: 'descricao_resumida', label: 'Descrição resumida', type: 'text', required: true, maxLength: 255, listed: true, searchable: true, span: 2, secao: 'Consulta' },
      { name: 'descricao_detalhada', label: 'Descrição detalhada', type: 'textarea', span: 4, secao: 'Consulta' },
      { name: 'status', label: 'Status', type: 'enum', options: opcoes([['A', 'Ativa'], ['I', 'Inativa']]), default: 'A', listed: true, filterable: true, secao: 'Acesso' },
      // Sem ref a usuarios_niveis: as colunas têm collations diferentes e a comparação do rótulo falha no MySQL
      { name: 'nivel_usuario', label: 'Nível mínimo', type: 'enum', options: opcoes('ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((l) => [l, l] as [string, string])), default: 'Z', listed: true, secao: 'Acesso', hint: 'Usuários com esta letra ou menor veem a consulta' },
      { name: 'usuarios_liberados', label: 'Usuários liberados', type: 'text', maxLength: 255, span: 2, secao: 'Acesso', hint: 'Ids dos usuários separados por vírgula; em branco = todos do nível' },
      { name: 'parametros', label: 'Parâmetros', type: 'textarea', span: 4, secao: 'Parâmetros', hint: 'Uma linha por parâmetro: parN=Rótulo;nome;Tipo (D/I/N/T/L/P);Padrão;Extra. No SQL: :nome' },
      ...[1, 2, 3, 4].flatMap((n): FieldDef[] => [
        { name: `sql${n}`, label: `SQL ${n}`, type: 'textarea', span: 4, secao: `SQL ${n}`, hint: n === 1 ? 'Só SELECT/WITH. Título da aba: /* t: Título */. Use :id_grupo e :id_empresa para filtrar pela empresa ativa' : undefined },
        { name: `sql${n}_titulos`, label: `Títulos do SQL ${n}`, type: 'textarea', span: 4, secao: `SQL ${n}`, hint: n === 1 ? 'Uma linha por campo: campo=Título;largura;formato (ex.: valor=Valor;120;,0.00)' : undefined },
      ]),
      { name: 'pivot_linhas', label: 'Cubo: linhas', type: 'textarea', span: 4, secao: 'Cubo', hint: 'Campos do SQL 1, um por linha' },
      { name: 'pivot_colunas', label: 'Cubo: colunas', type: 'textarea', span: 4, secao: 'Cubo' },
      { name: 'pivot_metrica', label: 'Cubo: valores', type: 'textarea', span: 4, secao: 'Cubo' },
    ],
  },
];
