import type { ResourceDef } from '../schema.js';
import { BASE, DA_EMPRESA, DO_GRUPO, ID, opcoes, sn } from './comum.js';

/**
 * Recursos do CRUD genérico do módulo Vendas (nome = tabela). A tela Vendas é própria (src/modulos/vendas);
 * aqui ficam os cadastros que ela usa (operações, séries, condições, fórmulas de imposto), editáveis pela
 * janela "Tabelas" da tela, e os movimentos só para consulta (vendas, itens, NF-e, títulos): a gravação
 * deles passa pelas rotas de server/vendas.ts, que aplicam as regras do Delphi.
 */
const SO_LEITURA = { canCreate: false, canUpdate: false, canDelete: false };

/** Filhos de uma venda: escopo pela venda do grupo/empresa ativos */
const DA_VENDA = (col: string) => ({
  scopeSql: `EXISTS (SELECT 1 FROM vendas V WHERE V.id = t.${col} AND V.id_grupo = :grupo AND V.id_empresa = :empresa)`,
});

const STATUS_VENDA = opcoes([
  ['A', 'Editando'],
  ['F', 'Finalizado'],
  ['R', 'Orçamento não confirmado'],
  ['C', 'Orçamento confirmado'],
  ['P', 'Pedido capturado'],
]);

const dinheiro = (name: string, label: string, extra: Record<string, unknown> = {}) => ({ name, label, type: 'decimal' as const, scale: 2, ...extra });

export const RECURSOS_VENDAS: ResourceDef[] = [
  {
    ...BASE,
    ...DA_EMPRESA,
    ...SO_LEITURA,
    name: 'vendas',
    table: 'vendas',
    label: 'Vendas',
    labelSingular: 'Venda',
    description: 'Vendas, orçamentos, pedidos e devoluções (gravação pela tela Vendas)',
    icon: 'ShoppingCart',
    group: 'vendas',
    oculto: true,
    labelField: 'numero',
    defaultSort: { field: 'id', dir: 'desc' },
    fields: [
      ID,
      { name: 'data_venda', label: 'Data venda', type: 'date', listed: true, filterable: true },
      { name: 'id_operacao', label: 'Operação', type: 'number', listed: true, filterable: true, ref: { resource: 'vendas_operacoes', labelField: 'apelido' } },
      { name: 'serie', label: 'Série', type: 'text', listed: true, width: 'xs' },
      { name: 'numero', label: 'Número', type: 'text', listed: true, searchable: true },
      { name: 'id_cliente', label: 'Cliente', type: 'number', listed: true, filterable: true, ref: { resource: 'pessoas', labelField: 'nome' } },
      { name: 'id_condicao', label: 'Condição', type: 'number', listed: true, ref: { resource: 'vendas_condicoes', labelField: 'apelido' } },
      { name: 'id_vendedor1', label: 'Vendedor 1', type: 'number', ref: { resource: 'vendedores', labelField: 'nome' } },
      { name: 'id_vendedor2', label: 'Vendedor 2', type: 'number', ref: { resource: 'vendedores', labelField: 'nome' } },
      dinheiro('valor_total_bruto', 'Total bruto'),
      dinheiro('valor_acrescimo_total', 'Acréscimos'),
      dinheiro('valor_desconto_total', 'Descontos'),
      dinheiro('valor_total_liquido', 'Total líquido', { listed: true }),
      { name: 'status', label: 'Status', type: 'enum', listed: true, filterable: true, options: STATUS_VENDA, width: 'sm' },
      { name: 'nfe_chave', label: 'Chave NF-e', type: 'text', searchable: true },
      { name: 'nfe_status', label: 'Status NF-e', type: 'text', listed: true, width: 'xs' },
      { name: 'obs', label: 'Observações', type: 'textarea', span: 4 },
    ],
    details: [
      { resource: 'vendas_produtos', foreignKey: 'id_venda', label: 'Produtos', totalField: 'valor_total_liquido_final' },
      { resource: 'areceber', foreignKey: 'id_venda', label: 'Parcelas', totalField: 'valor_areceber' },
    ],
  },
  {
    ...BASE,
    ...DA_VENDA('id_venda'),
    ...SO_LEITURA,
    name: 'vendas_produtos',
    table: 'vendas_produtos',
    label: 'Produtos da venda',
    labelSingular: 'Produto da venda',
    description: 'Itens das vendas',
    icon: 'Package',
    group: 'vendas',
    oculto: true,
    labelField: 'referencia',
    defaultSort: { field: 'item', dir: 'asc' },
    fields: [
      ID,
      { name: 'item', label: 'Item', type: 'number', listed: true, width: 'xs' },
      { name: 'id_venda', label: 'Venda', type: 'number' },
      { name: 'id_produto', label: 'Produto', type: 'number', listed: true, ref: { resource: 'produtos', labelField: 'descricao' } },
      { name: 'referencia', label: 'Referência', type: 'text', listed: true },
      { name: 'qtdade', label: 'Qtdade.', type: 'decimal', scale: 3, listed: true },
      dinheiro('preco_venda', 'Preço venda', { listed: true }),
      dinheiro('valor_total_bruto', 'Valor bruto', { listed: true }),
      dinheiro('valor_acrescimo_total', 'R$ acrésc.', { listed: true }),
      dinheiro('valor_desconto_total', 'R$ desc.', { listed: true }),
      dinheiro('valor_total_liquido_final', 'Valor líquido', { listed: true }),
      { name: 'cfop', label: 'CFOP', type: 'text', listed: true, width: 'xs' },
      { name: 'qtdade_devol', label: 'Qtd. devolv./fatur.', type: 'decimal', scale: 3 },
      { name: 'id_vendas_produtos_devol', label: 'Id de origem', type: 'number' },
    ],
  },
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'vendas_operacoes',
    table: 'vendas_operacoes',
    label: 'Operações de venda',
    labelSingular: 'Operação',
    description: 'Venda, devolução, pedido e orçamento: séries aceitas, entrada/saída e estoque',
    icon: 'ArrowLeftRight',
    group: 'vendas',
    oculto: true,
    labelField: 'apelido',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      { name: 'codigo', label: 'Código', type: 'enum', required: true, listed: true, width: 'xs', options: opcoes([['VEN', 'VEN - Venda'], ['DEV', 'DEV - Devolução'], ['PED', 'PED - Pedido'], ['ORC', 'ORC - Orçamento']]) },
      { name: 'apelido', label: 'Apelido', type: 'text', required: true, listed: true, searchable: true, maxLength: 20 },
      { name: 'descricao', label: 'Descrição (natureza da operação)', type: 'text', listed: true, maxLength: 50, span: 2 },
      { name: 'tipo', label: 'Tipo', type: 'enum', required: true, listed: true, width: 'xs', options: opcoes([['V', 'Venda'], ['D', 'Devolução (gera vale)']]), default: 'V' },
      { name: 'es', label: 'E/S', type: 'enum', required: true, listed: true, width: 'xs', options: opcoes([['S', 'Saída'], ['E', 'Entrada']]), default: 'S' },
      sn('mov_estoque', 'Movimenta estoque', { listed: true, default: true }),
      { name: 'series_aceitas', label: 'Séries aceitas', type: 'text', listed: true, maxLength: 60, hint: 'Separadas por ";" (ex.: 01;02). A primeira é a padrão.' },
      { name: 'cor', label: 'Cor', type: 'cor', listed: true, default: '#008080' },
    ],
  },
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'vendas_series',
    table: 'vendas_series',
    label: 'Séries de venda',
    labelSingular: 'Série',
    description: 'Séries e numeração das vendas (modelo 55 = NF-e)',
    icon: 'Hash',
    group: 'vendas',
    oculto: true,
    labelField: 'serie',
    defaultSort: { field: 'serie', dir: 'asc' },
    fields: [
      ID,
      { name: 'serie', label: 'Série', type: 'text', required: true, listed: true, maxLength: 3, width: 'xs' },
      { name: 'modelo', label: 'Modelo', type: 'text', listed: true, maxLength: 2, width: 'xs', hint: '55 = NF-e (abre o gerenciamento de NF-e)' },
      { name: 'descricao', label: 'Descrição', type: 'text', listed: true, maxLength: 40, span: 2 },
      { name: 'tipo', label: 'Tipo', type: 'enum', listed: true, width: 'xs', options: opcoes([['V', 'Venda (emite boleto)'], ['O', 'Outros']]), default: 'V' },
      { name: 'ultimo', label: 'Último número', type: 'number', listed: true },
      sn('ativo', 'Ativa', { listed: true, default: true }),
    ],
  },
  {
    ...BASE,
    ...DO_GRUPO,
    name: 'vendas_condicoes',
    table: 'vendas_condicoes',
    label: 'Condições de pagamento',
    labelSingular: 'Condição',
    description: 'Planos de pagamento das vendas: parcelas, entrada, intervalo e juros/desconto',
    icon: 'CalendarClock',
    group: 'vendas',
    oculto: true,
    labelField: 'apelido',
    defaultSort: { field: 'index', dir: 'asc' },
    fields: [
      ID,
      // `index` é palavra reservada e o INSERT/UPDATE do CRUD genérico não põe crases: só leitura (ver relatório)
      { name: 'index', label: 'Ordem', type: 'text', listed: true, readOnly: true, maxLength: 2, width: 'xs' },
      { name: 'apelido', label: 'Apelido', type: 'text', required: true, listed: true, searchable: true, maxLength: 25, hint: '"VALE" é a condição usada nas devoluções; "VISTA" no nome libera a venda ao consumidor' },
      { name: 'descricao', label: 'Descrição', type: 'text', listed: true, maxLength: 50, span: 2 },
      { name: 'nr_parcelas', label: 'Parcelas', type: 'number', required: true, listed: true, width: 'xs' },
      sn('entrada', 'Com entrada', { listed: true }),
      { name: 'intervalo', label: 'Intervalo (dias)', type: 'number', listed: true, hint: '7, 15, 21 e 30 contam em semanas/mês' },
      { name: 'juros_mes', label: 'Juros (%)', type: 'decimal', scale: 2, allowNegative: true, listed: true, hint: 'Negativo = desconto' },
      { name: 'id_banco', label: 'Banco', type: 'number', ref: { resource: 'bancos', labelField: 'apelido' } },
      sn('aceita_desconto', 'Aceita desconto', { default: true }),
      sn('ativo', 'Ativa', { listed: true, default: true }),
    ],
  },
  {
    ...BASE,
    name: 'nfe_impostos_formulas',
    table: 'nfe_impostos_formulas',
    label: 'Fórmulas de imposto',
    labelSingular: 'Fórmula',
    description: 'Scripts de cálculo dos impostos por UF, operação, NCM, produto e cliente (a tabela não tem grupo)',
    icon: 'FunctionSquare',
    group: 'vendas',
    oculto: true,
    labelField: 'imposto',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      { name: 'imposto', label: 'Imposto', type: 'text', listed: true, maxLength: 10 },
      { name: 'uf', label: 'UFs', type: 'text', required: true, listed: true, searchable: true, maxLength: 255, hint: 'Lista separada por ";" (UF do cliente)' },
      { name: 'operacao_codigo', label: 'Operações', type: 'text', listed: true, maxLength: 3, hint: 'VEN, DEV, PED ou ORC' },
      { name: 'ncm', label: 'NCMs', type: 'text', listed: true, maxLength: 255 },
      { name: 'id_produto', label: 'Produtos (ids)', type: 'text', listed: true, maxLength: 255 },
      { name: 'id_cliente', label: 'Clientes (ids)', type: 'text', listed: true, maxLength: 255 },
      { name: 'tipo_imposto_produto', label: 'Tipos de produto', type: 'text', maxLength: 255 },
      { name: 'tipo_imposto_cliente', label: 'Tipos de cliente', type: 'text', maxLength: 255 },
      { name: 'script_calculo', label: 'Script de cálculo', type: 'textarea', span: 4, hint: 'Portugol: <SE> … <ENTAO> … <SENAO> … <FIM>, ou IF … THEN { … } ELSE { … }. Atribuição com :=' },
    ],
  },
  {
    ...BASE,
    ...DA_VENDA('id_venda'),
    ...SO_LEITURA,
    name: 'nfe',
    table: 'nfe',
    label: 'NF-e',
    labelSingular: 'NF-e',
    description: 'Situação da NF-e de cada venda',
    icon: 'FileCheck',
    group: 'vendas',
    oculto: true,
    labelField: 'nfe_chave',
    defaultSort: { field: 'id', dir: 'desc' },
    fields: [
      ID,
      { name: 'id_venda', label: 'Venda', type: 'number', listed: true },
      { name: 'nfe_chave', label: 'Chave', type: 'text', listed: true, searchable: true },
      { name: 'nfe_status', label: 'Status', type: 'text', listed: true, width: 'xs' },
      { name: 'nfe_protocolo', label: 'Protocolo', type: 'text', listed: true },
      { name: 'nfe_recibo', label: 'Recibo', type: 'text' },
      { name: 'nfe_data_aut', label: 'Autorizada em', type: 'date', listed: true },
      { name: 'nfe_hora_aut', label: 'Hora', type: 'time' },
      { name: 'nfe_ultima_msg', label: 'Última mensagem', type: 'text', listed: true },
      { name: 'nfe_cancelada', label: 'Cancelada', type: 'text', listed: true, width: 'xs' },
      { name: 'nfe_protocolo_cancelamento', label: 'Protocolo cancelamento', type: 'text' },
    ],
  },
  {
    ...BASE,
    ...DA_VENDA('id_venda'),
    ...SO_LEITURA,
    name: 'nfe_eventos',
    table: 'nfe_eventos',
    label: 'Eventos de NF-e',
    labelSingular: 'Evento',
    description: 'Cartas de correção e cancelamentos registrados',
    icon: 'FileClock',
    group: 'vendas',
    oculto: true,
    labelField: 'descricao',
    defaultSort: { field: 'id', dir: 'asc' },
    fields: [
      ID,
      { name: 'id_venda', label: 'Venda', type: 'number' },
      { name: 'seq', label: 'Seq#', type: 'text', listed: true, width: 'xs' },
      { name: 'data', label: 'Data', type: 'date', listed: true },
      { name: 'hora', label: 'Hora', type: 'time', listed: true },
      { name: 'protocolo', label: 'Protocolo', type: 'text', listed: true },
      { name: 'descricao', label: 'Descrição', type: 'text', listed: true },
      { name: 'texto', label: 'Texto', type: 'text' },
    ],
  },
  {
    ...BASE,
    ...DA_EMPRESA,
    ...SO_LEITURA,
    name: 'nfe_log',
    table: 'nfe_log',
    label: 'Log de NF-e',
    labelSingular: 'Registro',
    description: 'Mensagens das operações com a SEFAZ',
    icon: 'ScrollText',
    group: 'vendas',
    oculto: true,
    labelField: 'log',
    defaultSort: { field: 'id', dir: 'desc' },
    fields: [
      ID,
      { name: 'id_venda', label: 'Venda', type: 'number', listed: true },
      { name: 'data_hora', label: 'Registrado em', type: 'datetime', listed: true },
      { name: 'log', label: 'Mensagem', type: 'text', listed: true, searchable: true },
    ],
  },
  {
    ...BASE,
    ...DA_VENDA('id_venda'),
    ...SO_LEITURA,
    name: 'nfe_impostos',
    table: 'nfe_impostos',
    label: 'Totais de impostos',
    labelSingular: 'Total de impostos',
    description: 'Totais da NF-e calculados pelas fórmulas',
    icon: 'Sigma',
    group: 'vendas',
    oculto: true,
    labelField: 'id_venda',
    defaultSort: { field: 'id', dir: 'desc' },
    fields: [
      ID,
      { name: 'id_venda', label: 'Venda', type: 'number', listed: true },
      ...(['vBC', 'vICMS', 'vBCST', 'vST', 'vProd', 'vFrete', 'vSeg', 'vDesc', 'vII', 'vIPI', 'vPIS', 'vCOFINS', 'vOutro', 'vNF', 'vTotTrib', 'vFCPUFDest', 'vICMSUFDest', 'vICMSUFRemet'] as const).map((c) =>
        dinheiro(`icms_${c}`, c, { listed: ['vBC', 'vICMS', 'vProd', 'vNF'].includes(c) }),
      ),
    ],
  },
  {
    ...BASE,
    scopeSql:
      'EXISTS (SELECT 1 FROM vendas_produtos P JOIN vendas V ON V.id = P.id_venda WHERE P.id = t.id_vendas_produtos AND V.id_grupo = :grupo AND V.id_empresa = :empresa)',
    ...SO_LEITURA,
    name: 'nfe_impostos_produtos',
    table: 'nfe_impostos_produtos',
    label: 'Impostos dos itens',
    labelSingular: 'Impostos do item',
    description: 'Impostos de cada item calculados pelas fórmulas',
    icon: 'Receipt',
    group: 'vendas',
    oculto: true,
    labelField: 'cfop',
    defaultSort: { field: 'id', dir: 'desc' },
    fields: [
      ID,
      { name: 'id_vendas_produtos', label: 'Item', type: 'number', listed: true },
      { name: 'empresa_CRT', label: 'CRT', type: 'text', width: 'xs' },
      { name: 'cfop', label: 'CFOP', type: 'text', listed: true },
      { name: 'icms_orig', label: 'Origem', type: 'text' },
      { name: 'icms_CST', label: 'CST', type: 'text', listed: true },
      { name: 'icms_CSOSN', label: 'CSOSN', type: 'text', listed: true },
      dinheiro('icms_vBC', 'BC ICMS', { listed: true }),
      { name: 'icms_pICMS', label: '% ICMS', type: 'decimal', scale: 4, listed: true },
      dinheiro('icms_vICMS', 'ICMS', { listed: true }),
      dinheiro('icms_vBCST', 'BC ST'),
      dinheiro('icms_vICMSST', 'ICMS ST'),
      { name: 'ipi_cst', label: 'CST IPI', type: 'text' },
      dinheiro('ipi_vIPI', 'IPI'),
      { name: 'pis_CST', label: 'CST PIS', type: 'text' },
      dinheiro('pis_vPIS', 'PIS'),
      { name: 'cofins_CST', label: 'CST COFINS', type: 'text' },
      dinheiro('cofins_vCOFINS', 'COFINS'),
    ],
  },
  // areceber: recurso do módulo Faturamento (server/recursos/faturamento.ts)
  {
    ...BASE,
    ...DA_EMPRESA,
    ...SO_LEITURA,
    name: 'areceber_vales',
    table: 'areceber_vales',
    label: 'Vales',
    labelSingular: 'Vale',
    description: 'Vales gerados pelas devoluções',
    icon: 'Ticket',
    group: 'vendas',
    oculto: true,
    labelField: 'numero',
    defaultSort: { field: 'id', dir: 'desc' },
    fields: [
      ID,
      { name: 'numero', label: 'Número', type: 'text', listed: true, searchable: true },
      { name: 'id_venda', label: 'Venda', type: 'number', listed: true },
      { name: 'id_cliente', label: 'Cliente', type: 'number', listed: true, ref: { resource: 'pessoas', labelField: 'nome' } },
      { name: 'data_geracao', label: 'Gerado em', type: 'date', listed: true },
      { name: 'data_vencimento', label: 'Vencimento', type: 'date', listed: true },
      dinheiro('valor', 'Valor', { listed: true }),
      dinheiro('valor_usado', 'Usado', { listed: true }),
      { name: 'status', label: 'Status', type: 'text', listed: true, width: 'xs' },
    ],
  },
];
